# Generated by Django 4.1.7 on 2023-07-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pesos',
            field=models.ManyToManyField(blank=True, default=None, related_name='rutinas_semana', to='plataforma.peso'),
        ),
    ]
