# Generated by Django 4.1.7 on 2023-08-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_user_pesos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='todos_ejercicios',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(upload_to='plataforma/static/plataforma/imagenes'),
        ),
        migrations.CreateModel(
            name='Relacion_RyE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ej', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ej', to='plataforma.ejercicio')),
                ('rutina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='plataforma.rutina')),
            ],
        ),
    ]
