# Generated by Django 4.1.7 on 2023-08-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_remove_rutina_todos_ejercicios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion_rye',
            name='orden',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
