# Generated by Django 4.1.7 on 2023-08-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_relacion_rye_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizarron',
            name='rutinas_semana',
        ),
        migrations.CreateModel(
            name='Relacion_PyR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(blank=True, max_length=128, null=True)),
                ('pizarron_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pizarron_id', to='plataforma.pizarron')),
                ('pizarron_rutina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pizarron_rutina', to='plataforma.rutina')),
            ],
        ),
    ]
