# Generated by Django 4.1.7 on 2023-08-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_remove_pizarron_rutinas_semana_relacion_pyr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='fecha_cambio',
            field=models.DateField(blank=True, default=None),
        ),
    ]
