# Generated by Django 4.1.7 on 2023-08-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_peso_fecha_cambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peso',
            name='fecha_cambio',
        ),
    ]
