# Generated by Django 4.1.7 on 2023-08-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_remove_peso_fecha_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio', to='plataforma.ejercicio'),
        ),
    ]
