# Generated by Django 4.1.7 on 2023-08-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alter_peso_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
