# Generated by Django 4.1.7 on 2023-08-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_peso_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='tipo_sexo',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
