# Generated by Django 4.1.7 on 2023-09-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_alter_ejercicio_descanso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
